import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("LoanApprovalPrediction.csv")
data['LoanAmount'].fillna(data['LoanAmount'].mean(),inplace=True)
data['Credit_History'].fillna(0,inplace=True)
data.drop('Dependents',inplace=True,axis=1)
data.drop('Loan_Amount_Term',inplace=True,axis=1)
data.drop('Property_Area',inplace=True,axis=1)
print(data)
print(data.isnull().sum())
data.sort_values(by='LoanAmount',ascending=True)
plt.plot(data['LoanAmount'],data['Loan_Status'],c='red')
plt.show()
plt.scatter(data['LoanAmount'],data['Loan_Status'],alpha=0.5)
plt.show()
plt.bar(data['LoanAmount'],data['Loan_Status'])
plt.show()
